name: pre-merge

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Install tox
        run: python -m pip install tox
      - name: Run Tests with Tox
        run: tox
